repos:
  # Python linting and formatting (for Python scripts only)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
        files: ^scripts/.*\.py$
      - id: ruff-format
        files: ^scripts/.*\.py$

  # Essential file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-ast  # Verify Python syntax
        files: ^scripts/.*\.py$
      - id: detect-private-key

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*\.lock$|package-lock\.json$|.*\.example$|credentials/

  # Shell script checks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^(cluster-deploy|scripts/.*\.sh)$

  # Essential project checks
  - repo: local
    hooks:
      - id: smoke-test
        name: Run smoke tests
        entry: python3 scripts/smoke-test.py --quiet
        language: system
        pass_filenames: false
        always_run: true

      - id: check-deployment-script
        name: Check deployment script syntax
        entry: bash -n cluster-deploy
        language: system
        files: ^cluster-deploy$
        pass_filenames: false

      - id: check-aws-credentials
        name: Ensure no AWS credentials in code
        entry: bash -c '! grep -r "AKIA\|aws_access_key_id\|aws_secret_access_key" scripts/ instance/ --include="*.py" --include="*.sh" --include="*.yaml"'
        language: system
        pass_filenames: false

ci:
  skip: [shellcheck, smoke-test, check-deployment-script, check-aws-credentials]  # These might not work in CI
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  submodules: false
