repos:
  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --check-untyped-defs, --no-strict-optional, --disable-error-code=no-any-return, --disable-error-code=unused-ignore]
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - boto3-stubs[ec2]
        files: ^spot_deployer/
        exclude: ^tests/

  # Essential file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^.github/workflows/
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: check-ast  # Verify Python syntax
      - id: detect-private-key
        exclude: ^tests/

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*\.lock$|package-lock\.json$|.*\.example$

  # Python security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ['-ll', '--skip', 'B101,B108,B202,B324,B601']
        files: ^spot_deployer/
        exclude: ^tests/

  # Essential project checks
  - repo: local
    hooks:
      - id: smoke-test
        name: Run smoke tests
        entry: uv run python scripts/smoke-test.py --quiet
        language: system
        pass_filenames: false
        always_run: true

      - id: check-aws-credentials
        name: Ensure no AWS credentials in code
        entry: bash -c '! grep -r "AKIA\|aws_access_key_id\|aws_secret_access_key" spot_deployer/ scripts/ --include="*.py"'
        language: system
        pass_filenames: false

ci:
  skip: [mypy, smoke-test, check-aws-credentials]  # These might not work in CI
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  submodules: false
