#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINFUxJyYOV4crJxJk/UW3gLvCANAD/y1uwDZtmbduKcc daaronch@M1-Max.local
    groups: docker

package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose-plugin
  - python3
  - python3-pip
  - wget
  - curl
  - git

write_files:
  - path: /opt/uploaded_files/orchestrator_endpoint
    content: |
      hch03d1vtvqqur.us1.cloud.expanso.io:4222
    owner: ubuntu:ubuntu
    permissions: '0644'
    
  - path: /opt/uploaded_files/orchestrator_token
    content: |
      GVqCNQKWUi76eP99ivfTbpyBP8zTCCuNKutHEmLDpUacMcYgwJF7ZuN6gRsq5Hur
    owner: ubuntu:ubuntu
    permissions: '0600'
    
  - path: /opt/bootstrap.sh
    content: |
      #!/bin/bash
      set -e
      
      echo "Starting bootstrap at $(date)" | tee -a /opt/startup.log
      
      # Clone the deployment files
      cd /opt
      git clone https://github.com/YOUR_REPO/spot.git deployment-repo || \
        (echo "Failed to clone repo" >> /opt/startup.log && exit 1)
      
      # Copy files to expected locations
      cp -r deployment-repo/instance/scripts /opt/uploaded_files/
      cp -r deployment-repo/instance/config /opt/uploaded_files/
      cp -r deployment-repo/files/* /opt/uploaded_files/ 2>/dev/null || true
      
      # Fix permissions
      chown -R ubuntu:ubuntu /opt/uploaded_files
      chmod +x /opt/uploaded_files/scripts/*.sh
      chmod +x /opt/uploaded_files/scripts/*.py
      
      # Create directories
      mkdir -p /bacalhau_node /bacalhau_data
      mkdir -p /opt/sensor/{config,data,logs,exports}
      chown -R ubuntu:ubuntu /bacalhau_node /bacalhau_data /opt/sensor
      
      # Install systemd services
      cp /opt/uploaded_files/scripts/*.service /etc/systemd/system/
      systemctl daemon-reload
      
      # Start services
      systemctl enable bacalhau-startup.service
      systemctl start bacalhau-startup.service
      
      echo "Bootstrap complete at $(date)" | tee -a /opt/startup.log
    owner: root:root
    permissions: '0755'

runcmd:
  - /opt/bootstrap.sh
