aws:
  total_instances: 80
  username: ubuntu
  public_ssh_key_path: /Users/daaronch/.ssh/id_ed25519.pub
  private_ssh_key_path: /Users/daaronch/.ssh/id_ed25519
  files_directory: instance-files
  scripts_directory: instance-files/usr/local/bin
  startup_script: instance-files/usr/local/bin/deploy_services.py
  cloud_init_template: instance/cloud-init/init-vm-template.yml
  instance_storage_gb: 20
  associate_public_ip: true
  use_dedicated_vpc: true
  tags:
    Project: Amauo
    Environment: Development
    ManagedBy: Amauo
    NodeCount: "80"
regions:
  - us-west-2:
      machine_type: t3.medium
      image: auto
  - us-east-1:
      machine_type: t3.medium
      image: auto
  - us-east-2:
      machine_type: t3.medium
      image: auto
  - eu-west-1:
      machine_type: t3.medium
      image: auto
  - eu-central-1:
      machine_type: t3.medium
      image: auto
  - eu-west-2:
      machine_type: t3.medium
      image: auto
  - ap-southeast-1:
      machine_type: t3.medium
      image: auto
  - ap-southeast-2:
      machine_type: t3.medium
      image: auto
  - ap-northeast-1:
      machine_type: t3.medium
      image: auto
  - ca-central-1:
      machine_type: t3.medium
      image: auto
