[project]
name = "aws-spot-deployer"
version = "0.1.0"
dependencies = [
    "boto3",
    "botocore",
    "rich",
    "aiosqlite",
    "aiofiles",
    "pyyaml",
]
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
