[project]
name = "spot-deployer"
version = "1.0.0"
description = "AWS Spot Instance Deployment Tool with Bacalhau support"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.26.0",
    "pyyaml>=6.0",
    "rich>=13.0.0",
]

[project.scripts]
spot-deployer = "spot_deployer.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["spot_deployer"]

[tool.uv]
dev-dependencies = [
    "ruff>=0.1.0",
    "pyright>=1.1.0",
    "pytest>=7.0.0",
]

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "I", "N", "W"]
ignore = ["E501"]  # Line too long

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "basic"