# Bacalhau Compute Node Configuration
# This file is copied to /bacalhau_node/config.yaml by the setup-config service

# Node name provider - uses hostname for unique identification
NameProvider: hostname

# Data directory for Bacalhau
DataDir: /bacalhau_data

# API Configuration
API:
  Host: 0.0.0.0
  Port: 1234

# Compute node configuration
Compute:
  Enabled: true
  # Orchestrators are configured via BACALHAU_COMPUTE_ORCHESTRATORS environment variable
  # Network port range for compute jobs
  Network:
    PortRangeStart: 20000
    PortRangeEnd: 30000
  # Heartbeat settings
  Heartbeat:
    InfoUpdateInterval: 1m0s
    Interval: 15s
  # Resource allocation - conservative for spot instances
  AllocatedCapacity:
    CPU: "70%"
    Memory: "70%"
    Disk: "50%"
    GPU: "0%"
  # Allow access to sensor data directories
  AllowListedLocalPaths:
    - "/opt/sensor/data:ro"
    - "/opt/sensor/exports:rw"
    - "/tmp:rw"
    - "/bacalhau_data:rw"

# Disable orchestrator mode
Orchestrator:
  Enabled: false

# Job admission control
JobAdmissionControl:
  Locality: anywhere

# Logging configuration
Logging:
  Level: info
  Mode: default
  LogDebugInfoInterval: 30s
