# Deployment Manifest
# This file defines what gets deployed to your instances

version: 1

deployment:
  # Create tarball from the bacalhau-deployment directory
  tarball_source: ./bacalhau-deployment
  
  # System packages to install via apt
  packages:
    - curl
    - wget
    - git
    - python3
    - python3-pip
    - docker.io
    - docker-compose

  # Scripts to run during setup (will be extracted from tarball)
  scripts:
    - name: setup
      path: scripts/setup.sh
      order: 1
    - name: setup-bacalhau
      path: /opt/deployment/bacalhau-deployment/setup-bacalhau.sh
      order: 2

  # SystemD services to install and start
  services:
    - name: bacalhau
      file: /opt/deployment/bacalhau-deployment/bacalhau.service
      enabled: true
      start: true
