# Deployment Manifest
# This file defines what gets deployed to your instances

version: 1

deployment:
  # System packages to install via apt
  packages:
    - curl
    - wget
    - git
    - python3
    - python3-pip
    - docker.io
    - docker-compose

  # Scripts to run during setup
  scripts:
    - name: setup
      path: scripts/setup.sh
      order: 1
    - name: setup-bacalhau
      path: scripts/setup-bacalhau.sh
      order: 2

  # Files to upload
  uploads:
    - source: configs/bacalhau-config.yaml
      destination: /opt/uploaded_files/bacalhau-config.yaml
      permissions: "644"
    - source: docker-compose.yml
      destination: /opt/uploaded_files/docker-compose.yml
      permissions: "644"

  # SystemD services to install and start
  services:
    - name: bacalhau
      file: services/bacalhau.service
      enabled: true
      start: true
