#cloud-config
# Minimal cloud-init template for spot deployer

users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL{{SSH_KEY_SECTION}}

packages: []
# {{PACKAGES}}

runcmd:
  - mkdir -p /opt/deployment
  - echo "Minimal deployment complete" > /opt/deployment.log
