services:
  sensor-generator:
    image: ghcr.io/bacalhau-project/sensor-log-generator:latest
    container_name: sensor-log-generator
    restart: unless-stopped
    volumes:
      - /opt/sensor/data:/app/data
      - /opt/sensor/logs:/app/logs
      - /opt/sensor/exports:/app/exports
      - /opt/sensor/config:/config:ro
    environment:
      - CONFIG_FILE=/config/sensor-config.yaml
      - IDENTITY_FILE=/config/node_identity.json
      - PYTHONUNBUFFERED=1
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
