services:
  bacalhau-node:
    image: ghcr.io/bacalhau-project/bacalhau:latest-dind
    container_name: bacalhau-node
    privileged: true
    restart: unless-stopped
    command: ["serve", "--config", "/etc/bacalhau/config.yaml"]
    volumes:
      - /bacalhau_node/config.yaml:/etc/bacalhau/config.yaml:ro
      - /bacalhau_node/node-info:/etc/node-info
      - /bacalhau_data:/bacalhau_data
    ports:
      - "1234:1234"  # API port
      - "4222:4222"  # NATS port
    environment:
      - BACALHAU_NODE_NETWORK_TYPE=libp2p
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/api/v1/agent/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"