# Bacalhau v1.x Compute Node Configuration Template
# This template has credentials injected during deployment

# Name provider for node identity
NameProvider: aws

# Data directory for Bacalhau
DataDir: /bacalhau_data

# Node identity - unique identifier for this node
Node:
  Name: "bacalhau-{{INSTANCE_ID}}"
  ClientID: "{{INSTANCE_ID}}"

# API Configuration
API:
  Host: 0.0.0.0
  Port: 1234

# Compute node configuration (new v1.x format)
Compute:
  Enabled: true
  Auth:
    Token: "{{ORCHESTRATOR_TOKEN}}"
  Orchestrators:
    - "{{ORCHESTRATOR_ENDPOINT}}"
  # Heartbeat settings
  Heartbeat:
    InfoUpdateInterval: 1m0s
    Interval: 15s
  # Resource allocation - conservative for spot instances
  AllocatedCapacity:
    CPU: "70%"
    Memory: "70%"
    Disk: "50%"
    GPU: "0%"
  # Allow access to sensor data directories
  AllowListedLocalPaths:
    - "/opt/sensor/data:ro"
    - "/opt/sensor/exports:rw"
    - "/tmp:rw"
    - "/bacalhau_data:rw"

# Disable orchestrator mode - this is a compute-only node
Orchestrator:
  Enabled: false

# Job admission control
JobAdmissionControl:
  Locality: anywhere

# Logging configuration
Logging:
  Level: info
  Mode: default
