version: '3.8'

x-common-env-variables: &common-env-variables
  BACALHAU_DISABLEANALYTICS: "true"
  LOG_LEVEL: info

services:
  compute:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    hostname: compute-${HOSTNAME:-node}
    command: serve -c /etc/bacalhau/config.yaml
    environment: *common-env-variables
    network_mode: "host"
    volumes:
      - /etc/bacalhau/config.yaml:/etc/bacalhau/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bacalhau", "version"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 15s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
