# Sensor Simulator Configuration
# This configuration defines how the sensor generates and exports data

# Data generation settings
generation:
  # Interval between sensor readings (seconds)
  interval: 30

  # Data types to generate
  sensors:
    - type: "temperature"
      unit: "celsius"
      range: [-10, 45]
      precision: 2

    - type: "humidity"
      unit: "percent"
      range: [20, 95]
      precision: 1

    - type: "pressure"
      unit: "hPa"
      range: [980, 1050]
      precision: 1

    - type: "light"
      unit: "lux"
      range: [0, 100000]
      precision: 0

    - type: "motion"
      unit: "boolean"
      # Boolean sensor with probability of true
      probability: 0.1

# Data storage
storage:
  # Local database file
  database: "/app/data/sensor_data.db"

  # Retention period (days)
  retention_days: 30

  # Batch size for database writes
  batch_size: 100

# Data export settings
export:
  # Export interval (seconds) - how often to export data
  interval: 300  # 5 minutes

  # Export formats
  formats:
    - "json"
    - "csv"

  # Local export directory
  local_directory: "/app/exports"

  # S3 export configuration (optional)
  s3:
    enabled: true
    bucket: "${S3_BUCKET_NAME}"
    prefix: "sensor-data/${NODE_ID}"
    region: "${AWS_DEFAULT_REGION}"

# Monitoring and health
monitoring:
  # Health check endpoint
  health_check_port: 8080

  # Metrics export
  metrics:
    enabled: true
    port: 8081

  # Log level
  log_level: "${LOG_LEVEL:-info}"

# Node identification
node:
  # Node identity file (generated at startup)
  identity_file: "/config/node_identity.json"

  # Additional metadata to include in exports
  metadata:
    deployment_type: "amauo"
    cloud_provider: "aws"
