## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
python3.pkg-path = "python3"
uv.pkg-path = "uv"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = """
  (
    # Create virtual environment if it doesn't exist
    if [ ! -d ".venv" ]; then
      echo "Creating Python virtual environment..." >&2
      python3 -m venv .venv
    fi
    
    source ".venv/bin/activate"
    # install the dependencies for this project based on pyproject.toml
    # <https://pip.pypa.io/en/stable/cli/pip_install/>
    pip install -e . --quiet
  )
"""


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
bash = """
  # Autogenerated by Flox

  if [ -d ".venv" ]; then
    echo "Activating python virtual environment" >&2
    source ".venv/bin/activate"
  fi

  # End autogenerated by Flox
"""
fish = """
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source ".venv/bin/activate.fish"

  # End autogenerated by Flox
"""
tcsh = """
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source ".venv/bin/activate.csh"

  # End autogenerated by Flox
"""
zsh = """
  # Autogenerated by Flox

  if [ -d ".venv" ]; then
    echo "Activating python virtual environment" >&2
    source ".venv/bin/activate"
  fi

  # End autogenerated by Flox
"""


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
