version: '3.8'

services:
  sensor-simulator:
    image: ghcr.io/bacalhau-project/sensor-log-generator:latest
    container_name: sensor-simulator
    pull_policy: always
    restart: unless-stopped

    environment:
      # Configuration files
      - CONFIG_FILE=/config/sensor-config.yaml
      - IDENTITY_FILE=/config/node_identity.json

      # AWS configuration for S3 uploads
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}

    volumes:
      # Configuration and identity
      - /opt/sensor/config:/config:ro

      # Data persistence
      - /opt/sensor/data:/app/data

      # Logs and exports
      - /opt/sensor/logs:/app/logs
      - /opt/sensor/exports:/app/exports

      # AWS credentials
      - /root/.aws:/root/.aws:ro
      - /home/ubuntu/.aws:/home/app/.aws:ro

    healthcheck:
      test: ["CMD-SHELL", "test -f /app/data/*.db || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

    labels:
      - "com.bacalhau.service=sensor"
      - "com.bacalhau.deployment=skypilot"
