name: Auto Create PR

on:
  push:
    branches: [develop]

jobs:
  create-pr:
    name: Create PR to Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check if PR needed
      id: check
      run: |
        # Check if develop is ahead of main
        git fetch origin main
        AHEAD=$(git rev-list --count origin/main..HEAD)
        echo "commits_ahead=$AHEAD" >> $GITHUB_OUTPUT

        # Check if PR already exists
        EXISTING_PR=$(gh pr list --base main --head develop --state open --json number --jq '.[0].number // empty')
        echo "existing_pr=$EXISTING_PR" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create PR
      if: steps.check.outputs.commits_ahead > 0 && steps.check.outputs.existing_pr == ''
      run: |
        gh pr create \
          --base main \
          --head develop \
          --title "🔄 Develop → Main" \
          --body "$(cat <<'EOF'
        ## Auto-generated PR

        This PR automatically merges changes from `develop` to `main`.

        ### Changes
        - ${{ steps.check.outputs.commits_ahead }} new commit(s) on develop

        ### Review Checklist
        - [ ] All CI checks pass
        - [ ] Changes are tested
        - [ ] Ready for release
        EOF
        )" \
          --label "auto-generated"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
