name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: |
        for i in {1..3}; do
          uv python install 3.11 && break
          echo "Failed to install python, retrying..."
          sleep 5
        done
    
    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-
    
    - name: Install dependencies
      run: uv sync
    
    - name: Lint with ruff
      run: |
        uv pip install --system ruff
        ruff check .
        ruff format --check .
    
    - name: Run tests
      run: |
        # Test the main module can be imported
        uv run python -c "import spot_deployer; print('Import successful')"
        
        # Test CLI help
        uv run python -m spot_deployer --help
        
        # Run any existing tests
        if [ -f test_simple.py ]; then
          uv run python test_simple.py
        fi
    
    - name: Test Docker build
      run: |
        # Test that the Docker image builds successfully
        docker build -t test-spot-deployer .
        
        # Test that the image runs
        docker run --rm test-spot-deployer help