name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Lint with ruff
        run: |
          uv run ruff check spot_deployer/
          uv run ruff format --check spot_deployer/

      - name: Run smoke tests
        run: |
          # Test CLI help command
          uv run python -m spot_deployer help

          # Test version command
          uv run python -m spot_deployer --version

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: test-spot-deployer:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Test that setup command works without config
          docker run --rm -v /tmp/test-output:/app/output test-spot-deployer:ci setup

          # Verify config was created
          test -f /tmp/test-output/config.yaml || exit 1
