name: CI

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Run ruff check
        run: uv run ruff check src/ tests/ scripts/

      - name: Run ruff format check
        run: uv run ruff format --check src/ tests/ scripts/

      - name: Run type checking
        run: uv run mypy src/amauo/ --ignore-missing-imports --check-untyped-defs

      - name: Run security check
        run: uv run bandit -r src/amauo/ -ll --skip B101,B108,B202,B324,B601

  test:
    name: Test Python 3.12
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: quality

    steps:
      - uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Run smoke tests
        run: uv run python scripts/smoke-test.py

      - name: Run tests
        run: uv run pytest tests/ -v
