name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --frozen --group dev

    - name: Run linting
      run: |
        uv run ruff check src/ tests/ scripts/ --exclude src/amauo/_version.py
        uv run ruff format --check src/ tests/ scripts/ --exclude src/amauo/_version.py

    - name: Run type checking
      run: uv run mypy src/amauo/ --ignore-missing-imports --check-untyped-defs --exclude _version.py

    - name: Run security check
      run: uv run bandit -r src/amauo/ -ll --skip B101,B108,B202,B324,B601

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Run smoke tests
      run: uv run python scripts/smoke-test.py

    - name: Test CLI installation
      run: uv run python -m amauo --version

  testpypi-deploy:
    name: Deploy to TestPyPI
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/amauo/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Generate development version
      run: |
        # Use hatch-vcs for dynamic versioning from git
        # The version will be automatically generated from git history
        echo "Using dynamic versioning from git tags via hatch-vcs"

        # Create timestamp-based development version for TestPyPI
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHORT_HASH=$(git rev-parse --short HEAD)

        # Get latest tag version
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        BASE_VERSION=${LATEST_TAG#v}
        DEV_VERSION="${BASE_VERSION}.dev${TIMESTAMP}"

        echo "Latest tag: $LATEST_TAG"
        echo "Base version: $BASE_VERSION"
        echo "Development version: $DEV_VERSION"
        echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_ENV

        # Generate _version.py for the build
        echo "__version__ = \"$DEV_VERSION\"" > src/amauo/_version.py

    - name: Build package
      run: uv build

    - name: Deploy to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true
