name: Publish Package
# This workflow publishes the Python package to PyPI
# Triggers on: version tags and manual dispatch

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  publish-package:
    name: Publish Python Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For PyPI trusted publishing

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Uses trusted publishing - no API token needed
