name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for changelog generation

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}
        body: |
          ## 🚀 Quick Start

          Install and deploy spot instances with uvx:

          ```bash
          # Install and run directly
          uvx --from git+https://github.com/${{ github.repository }} spot-deployer create

          # Or use the convenience script
          curl -sSL https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/install.sh | bash -s -- create
          ```

          ## Installation Options

          ### Option 1: uvx (Recommended)
          ```bash
          # One-time use
          uvx --from git+https://github.com/${{ github.repository }} spot-deployer help

          # Install globally
          uvx install --from git+https://github.com/${{ github.repository }} spot-deployer
          ```

          ### Option 2: PyPI Package
          ```bash
          pip install spot-deployer
          spot-deployer help
          ```

          ### Option 3: Local Development
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
          uv run python -m spot_deployer help
          ```

          ## What's Changed

          See the automated changelog below for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
